name: Build On Push

on:
  push:
    branches: 
      - '**'

jobs:
  javapos-workflow:
    uses: JavaPOSWorkingGroup/javapos-workflow/.github/workflows/build.yml@8dc874202d2b4361886ec52a2cfb515cf1a43c22
    with:
      github-event-action: ${{github.event.action}}
    secrets: inherit
