name: Build On Push

on:
  push:
    branches: 
      - '**'

jobs:
  javapos-build-workflow:
    uses: JavaPOSWorkingGroup/javapos-workflow/.github/workflows/build.yml@main
    with:
      github-event-action: ${{github.event.action}}
    secrets: inherit
