name: Build On Push

on:
  push:
    branches: 
      - '**'

jobs:
  javapos-workflow:
    uses: JavaPOSWorkingGroup/javapos-workflow/.github/workflows/build.yml@5f42cf026fcf74979e7b7a67d3582484c1d4ae9b
    with:
      github-event-action: ${{github.event.action}}
    secrets: inherit
