name: Release

on:
  release:
    types: [published]

jobs:
  javapos-build-workflow:
    uses: JavaPOSWorkingGroup/javapos-workflow/.github/workflows/release.yml@main
    with:
      github-event-action: ${{github.event.action}}
    secrets: inherit
